cart/urls.py
from django.urls import path
from . import views


app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>", views.cart_remove, name="cart_remove"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("", include("shop.urls", namespace="shop"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


app_name = "orders"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path("success/<int:order_id>", views.successful_order, name="successful_order"),
]

shop/urls.py
from django.urls import path
from . import views


app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>", views.product_list,
         name="product_list_by_category"),
    path("<int:id>/<slug:slug>", views.product_detail,
         name="product_detail")
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """
    This allows the user to select a quantity between one and 20.
    You use a TypedChoiceField field with coerce=int to convert
    the input into an integer.
    """
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)

    """
    This allows you to indicate whether the quantity has to be added to any 
    existing quantity in the cart for this product (False), or whether the existing
    quantity has to be overridden with the given quantity (True). 
    """
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    """
    The view for adding products to the cart or updating quantities
    for existing products. The require_POST decorator is used to allow
    only POST requests. The view receives the product ID as a parameter.
    The Product instance is retrieved with the given ID and validate CartAddProductForm.
    If the form is valid, you either add or update the product in the cart.
    The view redirects to the cart_detail URL.
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd["quantity"],
                 override_quantity=cd["override"])
        return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
    """
    The require_POST decorator is used to allow only POST requests.
    Retrieves the Product instance with the given ID
    and removes the product from the cart.
    Then, redirects the user to the cart_detail URL.
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(initial={
            "quantity": item["quantity"],
            "override": True
        })
    return render(request, "cart/detail.html", {"cart": cart})

cart/templates/cart/detail.html
<!--This is the template that is used to display the cart's contents.
It contains a table with the items stored in the current cart.
You allow users to change the quantity of the selected products using
a form that is posted to the cart_add view.
You also allow users to remove items from the cart by providing a
Remove button for each of them. Finally, you use an HTML form with
an action attribute that points to the cart_remove URL
including the product ID.-->



{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Your shopping cart
{% endblock %}

{% block content %}
<h1>Your shopping cart</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static 'img/no_image.png' %}{% endif %}">
            </a>
        </td>
        <td>{{ product.name }}</td>
        <td>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
            </form>
        </td>
        <td>
            <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
            </form>
        </td>
        <td class="num">${{ item.price }}</td>
        <td class="num">${{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button-light">
        Continue shopping
    </a>
    <a href="{% url 'orders:order_create' %}" class="button">
        Checkout
    </a>
</p>
{% endblock %}